# Generated by Django 4.1.5 on 2023-01-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
